@startmindmap
' Legend:
' Red: High priority
' Orange: medium priority
' Yellow: low priority
' Green: Very low priority
' Blue: Nice to have

+ DogTalk

++[#Red] User 
+++[#Red] User profile
++++ User name
++++ Profile image
++++ Birthday
++++[#Red] Group settings (for Admin)
+++++ List of member
++++++ Profile without credentials
+++++ Promote member
+++++ Invite member
+++++ Remove member
++++[#Red] Roll
+++++ Hundi
+++++ Trasureer
+++++ Administrator
++++[#Blue] Badges
+++++ "Königsblauer Hundi"
+++++ "Einsamer Wolf"
+++++ "Kassenwart"
+++++ "Alphahundi"
+++++ "Bester Stammtisch aller Zeiten"
+++++ "Schlechtester Stammtisch aller Zeiten"
++++[#Blue] Color theme

++[#Red] Log-In system
+++[#Red] Log-Out
++++ Time-Out
+++[#Red] Log-In data
++++ E-Mail
++++ Password

++[#Red] Sign-Up system
+++[#Red] Invite E-Mail
+++[#Red] Create new group
+++[#Red] Sign-Up data
++++ E-Mail
++++ Password

++[#Red] Calender
+++[#Green] Birthday
+++[#Red] Events
+++[#Red] Event date voting

++[#Orange] Status feed
+++[#Orange] Upcoming events
+++[#Green] Open event rating
+++[#Orange] Open date voting

++[#Yellow] Push messages
+++[#Yellow] Event reminder
+++[#Yellow] Voting reminder

--[#Orange] Penalties
---[#Orange] Penalty overview
---- Table
---[#Orange] Penalty management
----[#Orange] Add penalty
----[#Orange] Remove penalty
----[#Orange] Add penalty to user
-----[#Yellow] Efficient penalty interface
-----[#Yellow] Long press decision wheel

--[#Green] Random partner draw
---[#Green] Partner overview
---[#Green] Partner draw mechanism
---- Wheel of fortune
---- Drinking game
---- Slot mashine
---- Extendable

--[#Green] Event rating
---[#Green] Rating table with all events
---[#Green] Rate after event 

--[#Blue] Foto Dropbox
---[#Blue] Slide show
---[#Blue] Order by events

--[#Green] Social media links

--[#Blue] Order merchendise
---[#Blue] List of all merchendize
---[#Blue] Generate a order summary

--[#Red] UI design

--[#Orange] App icon
@endmindmap