@startmindmap
' Legend:
' Red: High priority
' Orange: medium priority
' Yellow: low priority
' Green: Very low priority
' Blue: Nice to have

+ DogTalk

++[#Red] User 
+++ Hundi
+++ Trasureer
+++ Administrator
+++ User profile
++++ User name
++++ Profile image
++++ Roll
++++ Badges
+++++ "Königsblauer Hundi"
+++++ "Einsamer Wolf"
+++++ "Kassenwart"
+++++ "Alphahundi"

++[#Red] Log-In system
+++ Log-Out
++++ Time-Out
+++ Log-In data
++++ E-Mail
++++ Password

++[#Red] Sign-Up system
+++ Invite E-Mail
+++ Create new group
+++ Sign-Up data
++++ E-Mail
++++ Password

++[#Red] Calender
+++ Birthday
+++ Events
+++ Event date voting

++[#Orange] Status feed
+++ Upcoming events
+++ Open event voting
+++ Open date voting

++[#Yellow] Push messages
+++ Event reminder
+++ Voting reminder

--[#Orange] Penalties
--- Penalty overview
---- Table
--- Penalty management
---- Add penalty
---- Remove penalty
---- Add penalty to user
----- Efficient penalty interface
----- Long press decision wheel

--[#Green] Random partner draw
--- Partner overview
--- Partner draw mechanism
---- Wheel of fortune
---- Drinking game
---- Slot mashine
---- Extendable

--[#Blue] Foto Dropbox
--- Slide show
--- Order by events

--[#Green] Social media links

--[#Blue] Order merchendise
--- List of all merchendize
--- Generate a order summary

@endmindmap